# Generated by Django 3.0.5 on 2020-04-26 11:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='Todo_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 26, 11, 40, 23, 991062, tzinfo=utc), null=True),
        ),
    ]
