# Generated by Django 3.0.5 on 2020-04-27 11:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200426_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Todo_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 27, 11, 25, 4, 801709, tzinfo=utc), null=True),
        ),
    ]
