# Generated by Django 3.0.5 on 2020-06-02 10:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20200427_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Todo_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 2, 10, 18, 3, 873162, tzinfo=utc), null=True),
        ),
    ]
