# Generated by Django 3.0.5 on 2020-06-02 11:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20200602_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Todo_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 2, 11, 20, 5, 884075, tzinfo=utc), null=True),
        ),
    ]
