# Generated by Django 3.0.5 on 2020-06-02 11:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20200602_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Todo_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 2, 11, 24, 7, 665383, tzinfo=utc), null=True),
        ),
    ]
