# Generated by Django 3.0.5 on 2020-06-02 21:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_auto_20200602_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Todo_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 2, 21, 57, 29, 696369, tzinfo=utc), null=True),
        ),
    ]
