# Generated by Django 3.0.5 on 2020-04-20 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todos',
            old_name='is_done',
            new_name='done_false',
        ),
        migrations.RenameField(
            model_name='todos',
            old_name='task',
            new_name='todo',
        ),
    ]
