# Generated by Django 3.0.5 on 2020-04-21 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20200421_0814'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todos',
            new_name='Try_todo',
        ),
    ]
